//! The channel listener: the socket the server and the hook connect to (§7.3, §6).
//!
//! One task accepts connections; each connection gets a reader (NDJSON to JSON-RPC,
//! validated against `channel.v1.schema.json`), a writer, and a [`Peer`] record. `hello` is
//! answered within 2 s: the token is compared in constant time, the protocol version has to
//! match exactly, and the peer is handed on as a [`ChannelEvent`] the store actor consumes
//! — where the ancestor chain is completed from the process table (DD-22, T-032) and a hook
//! gets its decision (T-035). Requests are dispatched on a single actor task, so every
//! state mutation is serialised.
//!
//! Named pipe with a DACL on Windows, Unix socket with the pointer file of FM-12 elsewhere.
//! The endpoint name is derived in [`endpoint`] and has to match, byte for byte, what
//! `handoff-mcp` derives on its side.
//!
//! # The four files
//!
//! - [`endpoint`] — where to listen, and what protects it: the pipe digest, the `sun_path`
//!   limit, the pointer file, the stale-socket rule, the DACL of A-16.
//! - [`token`] — `~/.handoff/channel.token`: generated once, owner-only, compared in
//!   constant time, regenerated by the repair action of the settings screen.
//! - [`listener`] — the accept loop, the framing, the handshake, the ping, the event stream.
//! - [`dispatch`] — the other end of that stream: the session registry, the store, and the
//!   outcomes that go back out as `handoff.event`.

pub mod dispatch;
pub mod endpoint;
pub mod listener;
pub mod token;

pub use dispatch::Dispatch;
pub use endpoint::{ensure_home, Endpoint};
pub use listener::{
    listen, ChannelEvent, ChannelHandle, ConnId, DisconnectReason, ListenerConfig, Peer, PeerRole,
    SendError,
};
pub use token::Token;

use std::io;

/// Prepares the shared folder, the token and the endpoint, and starts listening (§7.2).
///
/// This is the whole of the channel's part in the startup sequence: `~/.handoff/` and its
/// `runbooks/` folder exist afterwards, `channel.token` exists and is owner-only, and the
/// endpoint is bound. A server that started before the app is retrying with backoff (§5.3)
/// and connects on its next attempt, with no help from here.
///
/// # Errors
///
/// When the folder cannot be created, the token cannot be written, or the endpoint cannot
/// be bound — the last of which includes another instance already listening on it.
pub async fn start() -> io::Result<(ChannelHandle, tokio::sync::mpsc::Receiver<ChannelEvent>)> {
    let home = crate::paths::handoff_home();
    ensure_home(&home)?;
    let token = token::ensure(&crate::paths::token_path())?;
    listen(ListenerConfig::new(Endpoint::resolve(), token)).await
}
