//! Where the automation channel listens, and what protects it (DD-33, §11.5).
//!
//! A second endpoint beside the one of §6, derived the same way and from the same two
//! inputs, so that an e2e instance started with its own `HANDOFF_HOME` cannot land on the
//! endpoint of the app the owner is actually using (`TASKS.md` §0.4 item 4):
//!
//! - **Windows.** `\\.\pipe\handoff-e2e-<h>`, `h` being the digest
//!   [`crate::channel::endpoint::pipe_suffix`] computes for the product channel. One digest,
//!   two names: the pipe namespace is machine-global, and two harnesses running side by side
//!   under different homes must not meet.
//! - **Elsewhere.** `<HANDOFF_HOME>/e2e.sock`, mode `0600`, with the same `sun_path`
//!   fallback the product socket has (FM-12, A-17): when the path does not fit, the listener
//!   binds `<temp>/handoff-e2e-<h>.sock` and writes the real path into
//!   `<HANDOFF_HOME>/e2e.sock.path` for the harness to read.
//!
//! The token is `<HANDOFF_HOME>/e2e.token`, generated by [`crate::channel::token`] exactly
//! like `channel.token`: sixty-four hex characters in a file only this user can read, and
//! compared in constant time. It defends the same thing the product token defends — not a
//! process already running as the user, but every other user of the machine and every
//! accidental connection (§2.1) — and it matters more here, because what is behind it is a
//! control channel that presses the buttons.
//!
//! None of this is compiled into a build that does not ask for `--features e2e`: the module
//! itself is behind the feature, so the two names below exist in no shipped binary and
//! `scripts/check-no-automation.mjs` is what proves it.

use std::io;
use std::path::{Path, PathBuf};

use crate::channel::endpoint::{exceeds_sun_path, pipe_suffix, windows_user_key, Platform};
use crate::channel::token::Token;
use crate::paths;

/// The prefix of the automation pipe. The suffix is the product channel's digest.
pub const E2E_PIPE_PREFIX: &str = r"\\.\pipe\handoff-e2e-";

/// `<HANDOFF_HOME>/e2e.sock`.
pub const E2E_SOCKET_FILE_NAME: &str = "e2e.sock";

/// `<HANDOFF_HOME>/e2e.sock.path`, written only when the socket had to move (FM-12).
pub const E2E_SOCKET_POINTER_FILE_NAME: &str = "e2e.sock.path";

/// `<HANDOFF_HOME>/e2e.token`.
pub const E2E_TOKEN_FILE_NAME: &str = "e2e.token";

/// Where the automation channel listens.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum E2eEndpoint {
    /// `\\.\pipe\handoff-e2e-<h>`.
    Pipe {
        /// The full pipe name, prefix included.
        name: String,
    },
    /// A Unix domain socket, and the pointer file to write when it is not the path the
    /// harness derives on its own.
    Unix {
        /// What the listener binds.
        path: PathBuf,
        /// `<HANDOFF_HOME>/e2e.sock.path`, or nothing when `path` is the default.
        pointer: Option<PathBuf>,
    },
}

impl E2eEndpoint {
    /// The endpoint of this process, from the environment.
    #[must_use]
    pub fn resolve() -> Self {
        resolve_for(
            Platform::host(),
            &paths::handoff_home(),
            &windows_user_key(),
            paths::handoff_home_override().as_deref(),
            &std::env::temp_dir(),
        )
    }

    /// What a log line calls this endpoint.
    #[must_use]
    pub fn display(&self) -> String {
        match self {
            Self::Pipe { name } => name.clone(),
            Self::Unix { path, .. } => path.display().to_string(),
        }
    }

    /// The pointer file this endpoint needs, if any.
    #[must_use]
    pub fn pointer(&self) -> Option<&Path> {
        match self {
            Self::Pipe { .. } => None,
            Self::Unix { pointer, .. } => pointer.as_deref(),
        }
    }
}

/// The endpoint, from explicit inputs. The pure half of [`E2eEndpoint::resolve`], so both
/// shapes are exercised by the unit tests of every host and not only of the platform they
/// describe.
#[must_use]
pub fn resolve_for(
    platform: Platform,
    home: &Path,
    user_key: &str,
    home_override: Option<&str>,
    temp: &Path,
) -> E2eEndpoint {
    let suffix = pipe_suffix(user_key, home_override);
    if platform == Platform::Windows {
        return E2eEndpoint::Pipe {
            name: format!("{E2E_PIPE_PREFIX}{suffix}"),
        };
    }

    let default = home.join(E2E_SOCKET_FILE_NAME);
    if !exceeds_sun_path(&default) {
        return E2eEndpoint::Unix {
            path: default,
            pointer: None,
        };
    }

    let short = temp.join(format!("handoff-e2e-{suffix}.sock"));
    let path = if exceeds_sun_path(&short) {
        Path::new("/tmp").join(format!("handoff-e2e-{suffix}.sock"))
    } else {
        short
    };
    E2eEndpoint::Unix {
        path,
        pointer: Some(home.join(E2E_SOCKET_POINTER_FILE_NAME)),
    }
}

/// `<HANDOFF_HOME>/e2e.endpoint`: what the harness connects to, written once it is bound.
pub const E2E_ENDPOINT_FILE_NAME: &str = "e2e.endpoint";

/// `<HANDOFF_HOME>/e2e.token`.
#[must_use]
pub fn token_path() -> PathBuf {
    paths::handoff_home().join(E2E_TOKEN_FILE_NAME)
}

/// Writes the bound endpoint where the harness looks for it.
///
/// Written **after** the bind and never before: its existence is what tells the harness the
/// app is up, so a file written by an instance that then failed to bind would send every
/// scenario at an endpoint nobody is serving. A file left behind by a previous run of the
/// same temporary home is simply overwritten.
///
/// # Errors
///
/// When the file cannot be written.
pub fn publish(endpoint: &E2eEndpoint) -> io::Result<()> {
    std::fs::write(
        paths::handoff_home().join(E2E_ENDPOINT_FILE_NAME),
        format!("{}\n", endpoint.display()),
    )
}

/// The token of this run, written if it is not already there.
///
/// # Errors
///
/// When the file has to be written and cannot be.
pub fn ensure_token() -> io::Result<Token> {
    crate::channel::token::ensure(&token_path())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_pipe_carries_the_same_digest_as_the_product_channel() {
        let endpoint = resolve_for(
            Platform::Windows,
            Path::new(r"C:\Users\someone\.handoff"),
            r"domain\someone",
            None,
            Path::new(r"C:\Temp"),
        );
        let suffix = pipe_suffix(r"domain\someone", None);
        assert_eq!(
            endpoint,
            E2eEndpoint::Pipe {
                name: format!(r"\\.\pipe\handoff-e2e-{suffix}"),
            }
        );
        // The two names differ, or the harness would be talking to the product listener.
        assert_ne!(
            endpoint.display(),
            crate::channel::endpoint::pipe_name(r"domain\someone", None)
        );
    }

    #[test]
    fn an_isolated_home_moves_the_pipe() {
        let with = resolve_for(
            Platform::Windows,
            Path::new(r"C:\Temp\run\home"),
            r"domain\someone",
            Some(r"C:\Temp\run\home"),
            Path::new(r"C:\Temp"),
        );
        let without = resolve_for(
            Platform::Windows,
            Path::new(r"C:\Users\someone\.handoff"),
            r"domain\someone",
            None,
            Path::new(r"C:\Temp"),
        );
        assert_ne!(with, without);
    }

    #[test]
    fn the_socket_sits_in_the_home_when_the_path_fits() {
        let endpoint = resolve_for(
            Platform::Posix,
            Path::new("/Users/someone/.handoff"),
            "",
            None,
            Path::new("/tmp"),
        );
        assert_eq!(
            endpoint,
            E2eEndpoint::Unix {
                path: PathBuf::from("/Users/someone/.handoff/e2e.sock"),
                pointer: None,
            }
        );
        assert!(endpoint.pointer().is_none());
    }

    #[test]
    fn a_home_that_does_not_fit_moves_the_socket_and_leaves_a_pointer() {
        let home = PathBuf::from(format!("/Users/someone/{}", "d".repeat(120)));
        let endpoint = resolve_for(Platform::Posix, &home, "", None, Path::new("/tmp"));
        let E2eEndpoint::Unix { path, pointer } = endpoint else {
            panic!("a Unix endpoint");
        };
        assert!(!exceeds_sun_path(&path), "{} does not fit", path.display());
        assert_eq!(pointer, Some(home.join(E2E_SOCKET_POINTER_FILE_NAME)));
    }
}
